---
title: "EPPS 6323: Lab01 R programming basics I"
author: "Kayleigh Tompkins"
format: html
editor: visual
---

# R Programming Basic Commands

## Create object using the assignment operator (\<-, =)

```{r}
x <- c(1,3,2,5)
x
x = c(1,6,2)
x
y = c(1,4,3)
```

## Using function

```{r}
length(x)  # What does length() do? A: Counts how many elements are in an object. 
length(y)
```

## Using +, -, \*, /,\^ operators

```{r}
x+y
ls() # List objects in the environment
rm(x,y) # Remove objects
ls()
rm(list=ls()) # Danger! What does this do?  A: I'm not sure, it cleared my environment but so did rm(x,y)

```

## Matrix operations

```{r}
?matrix
x=matrix(data=c(1,2,3,4), nrow=2, ncol=2) # Create a 2x2 matrix object
x
x=matrix(c(1,2,3,4),2,2)
matrix(c(1,2,3,4),2,2,byrow=F) # What about byrow=F? A: This tells R to fill the matrix by putting 1 and 2 in the first column and then 3 and 4 in the second. In byrow=T, R fills the letters by row. 

sqrt(x) # What does x look like? A: It took the square root of every element in the matrix.
x
x^2

x=rnorm(50) # Generate a vector of 50 numbers using the rnorm() function

y=x+rnorm(50,mean=50,sd=.1) # What does rnorm(50,mean=50,sd=.1) generate? A: It generates y b y adding x to a vector of 50 random numbers which have a mean of 50 and a standard distribution of 0.1. 

cor(x,y) # Correlation of x and y
set.seed(1303) # Set the seed for Random Number Generator (RNG) to generate values that are reproducible.
rnorm(50)
set.seed(3) # Try different seeds?
y=rnorm(100)
```

## Simple descriptive statistics (base)

```{r}
mean(y)
var(y)
sqrt(var(y))
sd(y)
```

## Visualization using R Graphics (without packages)

```{r}


x=rnorm(100)
y=rnorm(100)
plot(x,y)

plot(x,y, pch=20, col = "firebrick") # Scatterplot for two numeric variables by default
plot(x,y, pch=20, col = "steelblue",xlab="this is the x-axis",ylab="this is the y-axis",main="Plot of X vs Y") # Add labels
pdf("Figure01.pdf") # Save as pdf, add a path or it will be stored on the project directory
plot(x,y,pch=20, col="forestgreen") # Try different colors?
dev.off() # Close the file using the dev.off function
x=seq(1,10) # Same as x=c(1:10)
x
x=1:10
x
x=seq(-pi,pi,length=50)
y=x

```
